name: iml.env
channels:
  - defaults
dependencies:
  - pandas
  - python=3.7
  - numpy
  - scipy
  - nb_conda_kernels
  - nb_conda
  - scikit-learn
  - psutil
  - requests
  - plotly-orca==1.2.1
  - plotly

